/*
 * Created by Marshall on 11/06/2015.
 */

// Import the uiautomator libraries

package org.opendatakit.common.android.utilities;

import android.support.test.InstrumentationRegistry;
import android.support.test.runner.AndroidJUnit4;
import android.support.test.uiautomator.UiDevice;
import android.support.test.uiautomator.UiObject;
import android.support.test.uiautomator.UiObjectNotFoundException;
import android.support.test.uiautomator.UiScrollable;
import android.support.test.uiautomator.UiSelector;
import android.test.InstrumentationTestCase;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(AndroidJUnit4.class)
public class UiTest extends InstrumentationTestCase {

    private static final long SURVEY_TIMEOUT = 5000; // timeout for loading survey from tables

    private UiDevice mDevice;

    @Before
    public void setUp() throws UiObjectNotFoundException { // Perform setup for UI Test

        // Init device
        injectInstrumentation(InstrumentationRegistry.getInstrumentation());
        mDevice = UiDevice.getInstance(getInstrumentation());

        // TODO: Kill any currently running tables instance

        // Start at home screen
        mDevice.pressHome();
        // TODO: add check for home screen

       // Goto all apps
        UiObject appButton = mDevice.findObject(new UiSelector()
                .description("Apps"));
        appButton.clickAndWaitForNewWindow();

       // Find the all-apps launcher listing screen
       UiObject appScreen = mDevice.findObject(new UiSelector()
            .resourceId("com.android.launcher:id/apps_customize_content"));

        // Find scroll pane within it
        UiScrollable appMenu = new UiScrollable(new UiSelector()
                .scrollable(true)
                .resourceId("com.android.launcher:id/apps_customize_pane_content"));
        appMenu.setAsHorizontalList();

        // Find ODK App
        UiObject odkApp = appMenu.getChildByText(new UiSelector()
                .className("android.widget.TextView"),
                "ODK Tables");
        odkApp.clickAndWaitForNewWindow();
    }

    @Test
    public void testUI() throws UiObjectNotFoundException, InterruptedException {

        // Click first screen menu
        UiObject menu1 = mDevice.findObject(new UiSelector()
                .resourceId("org.opendatakit.tables:id/menu_web_view_activity_table_manager"));
        menu1.clickAndWaitForNewWindow();

        // Scroll to and click Household Survey
        UiScrollable surveyList = new UiScrollable(new UiSelector()
                .scrollable(true)
                .className("android.widget.ListView"));
        UiObject householdSurvey = surveyList.getChildByText(new UiSelector()
                .className("android.widget.TextView"),
                "Household Survey");
        householdSurvey.clickAndWaitForNewWindow();

        // Handles potential checkpoint generated by sync
        discardCheckpoint();

        // Click addRow (launches Survey)
        UiObject addRow = mDevice.findObject(new UiSelector()
                .resourceId("org.opendatakit.tables:id/top_level_table_menu_add"));
        addRow.clickAndWaitForNewWindow();

        Thread.sleep(SURVEY_TIMEOUT);
        mDevice.click(50, 500); // TODO: Make this implementation less hacky

       Thread.sleep(500);
       // Click next
       WebUiObject nextButton = new WebUiObject(mDevice, new UiSelector()
           .className("android.widget.Button")
           .descriptionContains("next"));

       nextButton.click();

        // Fill textbox
        WebUiObject textBox = new WebUiObject(mDevice,new UiSelector()
                .className("android.widget.EditText"));
        textBox.setText(generateID());
        nextButton = new WebUiObject(mDevice, new UiSelector()
           .className("android.widget.Button")
           .descriptionContains("next"));
        nextButton.click();

        // Enter 7 into number of rooms
        textBox = new WebUiObject(mDevice,new UiSelector()
           .className("android.widget.EditText"));
        textBox.setText("7");
        nextButton = new WebUiObject(mDevice, new UiSelector()
           .className("android.widget.Button")
           .descriptionContains("next"));
        nextButton.click();

        // Return to previous screen and change to 17
        WebUiObject backButton = new WebUiObject(mDevice,new UiSelector()
                .className("android.widget.Button")
                .descriptionContains("back"));
        backButton.click();

        textBox = new WebUiObject(mDevice,new UiSelector()
           .className("android.widget.EditText"));
        textBox.setText("17");
        nextButton = new WebUiObject(mDevice, new UiSelector()
           .className("android.widget.Button")
           .descriptionContains("next"));
        nextButton.click();

       // electricity
        // Select yes
        WebUiObject yesRadioButton = new WebUiObject(mDevice,new UiSelector()
                .descriptionContains("yes")
                .className("android.widget.RadioButton"));
        yesRadioButton.click();
        nextButton = new WebUiObject(mDevice, new UiSelector()
           .className("android.widget.Button")
           .descriptionContains("next"));
        nextButton.click();

       // running water
        // Select no
        WebUiObject noRadioButton = new WebUiObject(mDevice,new UiSelector()
                .descriptionContains("no")
                .className("android.widget.RadioButton"));
        noRadioButton.click();

        // Reach end of form and finalize
        for (int i = 0; i < 9; i++) {
            nextButton = new WebUiObject(mDevice, new UiSelector()
               .className("android.widget.Button")
               .descriptionContains("next"));
            nextButton.click();
            Thread.sleep(500L);
        }

        // Click finalize
        UiObject finalizeButton = mDevice.findObject(new UiSelector()
                .className("android.widget.Button")
                .descriptionContains("Finalize"));
        finalizeButton.click();

       Thread.sleep(SURVEY_TIMEOUT);

       // Should find the addRow button (and be back in tables)
       addRow = mDevice.findObject(new UiSelector()
           .resourceId("org.opendatakit.tables:id/top_level_table_menu_add"));
    }

    private String generateID() { // TODO: Perhaps there's a better solution?
        int id = (int) (Math.random() * 101);
        return "household" + Integer.toString(id);
    }

    private void saveCheckpoint() { // save at checkpoint screen
        try {
            // Handle save screen
            UiObject saveButton = mDevice.findObject(new UiSelector()
                    .resourceId("org.opendatakit.sync:id/take_newest"));
            saveButton.click();

            // Handle confirmation pop-up
            UiObject yesButton = mDevice.findObject(new UiSelector()
                    .resourceId("android:id/button1"));
            yesButton.click();

        } catch (UiObjectNotFoundException e) {
            // Not a checkpoint
        }
    }

    private void discardCheckpoint() { // discard at checkpoint screen
        try {
            // Handle discard screen
            UiObject discardButton = mDevice.findObject(new UiSelector()
                    .resourceId("org.opendatakit.sync:id/take_oldest"));
            discardButton.click();

            // Handle confirmation pop-up
            UiObject yesButton = mDevice.findObject(new UiSelector()
                    .resourceId("android:id/button1"));
            yesButton.click();

        } catch (UiObjectNotFoundException e) {
            // Not a checkpoint
        }
    }
}
